services:
  app:
    build: .
    environment:
      - APP_ENV=${APP_ENV}
      - SERVER_NAME=${SERVER_NAME}
    ports:
      - "${APP_PORT_HTTP}:80"
      - "${APP_PORT_HTTPS}:443"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.125'
          memory: 64M
    volumes:
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
